
import Foundation

/// App 声明过的出站域名。唯一事实来源。
///
/// `ProviderCatalog` 里的控制台 URL、以后各家账单 API、以及打赏 Worker
/// 的 host，都必须能在 `all` 里找到。设置 → 关于列出 `visible`，
/// 所以加一个新域名等于同时改声明和界面，没有第二份要同步的清单。
///
/// `all` 是全集（`scripts/check-outbound-hosts.sh` 按它放行源码里的字面量）；
/// `visible` 是**当前这个壳真的会连**的那些，界面和运行时白名单都走它——
/// 只有 Mac 直发版会连的更新通道不该出现在 iPhone 的关于页上。
///
/// `reservedHosts` 只给 mock / 测试的 `.invalid` 占位用，不进关于页。
public enum OutboundHosts: Sendable {
    public static let all: [OutboundHost] = [
        OutboundHost(host: "api.cloudflare.com", purpose: L("Cloudflare 账单 API")),
        OutboundHost(host: "dash.cloudflare.com", purpose: L("Cloudflare 控制台与账单页")),
        OutboundHost(host: "developers.cloudflare.com", purpose: L("Cloudflare 查找 Account ID 文档")),
        OutboundHost(host: "console.neon.tech", purpose: L("Neon 控制台与账单 API")),
        OutboundHost(host: "ce.us-east-1.amazonaws.com", purpose: L("AWS Cost Explorer API")),
        OutboundHost(host: "console.aws.amazon.com", purpose: L("AWS 控制台与账单页")),
        OutboundHost(host: "api.openai.com", purpose: L("OpenAI 账单 API")),
        OutboundHost(host: "platform.openai.com", purpose: L("OpenAI 控制台与账单页")),
        OutboundHost(host: "api.anthropic.com", purpose: L("Anthropic 账单 API")),
        OutboundHost(host: "console.anthropic.com", purpose: L("Anthropic 控制台与账单页")),
        OutboundHost(host: "api.vercel.com", purpose: L("Vercel 账单 API")),
        OutboundHost(host: "vercel.com", purpose: L("Vercel 控制台与账单页")),
        OutboundHost(host: "api.github.com", purpose: L("GitHub 账单 API")),
        OutboundHost(host: "github.com", purpose: L("GitHub 控制台与账单页")),
        OutboundHost(host: "fly.io", purpose: L("Fly.io 控制台与账单页")),
        OutboundHost(host: "openrouter.ai", purpose: L("OpenRouter 控制台与账单 API")),
        OutboundHost(host: "api.deepseek.com", purpose: L("DeepSeek 账单 API")),
        OutboundHost(host: "platform.deepseek.com", purpose: L("DeepSeek 控制台与账单页")),
        OutboundHost(host: "api.moonshot.cn", purpose: L("Moonshot (China) 账单 API")),
        OutboundHost(host: "platform.kimi.com", purpose: L("Moonshot (China) 控制台与账单页")),
        OutboundHost(host: "api.moonshot.ai", purpose: L("Moonshot (Overseas) 账单 API")),
        OutboundHost(host: "platform.moonshot.ai", purpose: L("Moonshot (Overseas) 控制台与账单页")),
        OutboundHost(host: "management-api.x.ai", purpose: L("xAI 账单 API")),
        OutboundHost(host: "console.x.ai", purpose: L("xAI 控制台与账单页")),
        OutboundHost(host: "cursor.com", purpose: L("Cursor 控制台与账单页")),
        OutboundHost(host: "api.digitalocean.com", purpose: L("DigitalOcean 账单 API")),
        OutboundHost(host: "cloud.digitalocean.com", purpose: L("DigitalOcean 控制台与账单页")),
        OutboundHost(host: "api.twilio.com", purpose: L("Twilio 账单 API")),
        OutboundHost(host: "1console.twilio.com", purpose: L("Twilio 控制台与账单页")),
        OutboundHost(host: "api.planetscale.com", purpose: L("PlanetScale 账单 API")),
        OutboundHost(host: "app.planetscale.com", purpose: L("PlanetScale 控制台与账单页")),
        OutboundHost(host: "api.upstash.com", purpose: L("Upstash 账单 API")),
        OutboundHost(host: "console.upstash.com", purpose: L("Upstash 控制台与账单页")),
        OutboundHost(host: "api.elevenlabs.io", purpose: L("ElevenLabs 账单 API")),
        OutboundHost(host: "elevenlabs.io", purpose: L("ElevenLabs 控制台与账单页")),
        OutboundHost(host: "backboard.railway.com", purpose: L("Railway 账单 API")),
        OutboundHost(host: "railway.com", purpose: L("Railway 控制台与账单页")),
        OutboundHost(host: "api.stripe.com", purpose: L("Stripe 账单 API")),
        OutboundHost(host: "dashboard.stripe.com", purpose: L("Stripe 控制台与账单页")),
        OutboundHost(host: "api.resend.com", purpose: L("Resend 账单 API")),
        OutboundHost(host: "resend.com", purpose: L("Resend 控制台与账单页")),
        OutboundHost(host: "us.posthog.com", purpose: L("PostHog 账单 API")),
        OutboundHost(host: "eu.posthog.com", purpose: L("PostHog 欧盟账单 API")),
        OutboundHost(host: "app.posthog.com", purpose: L("PostHog 控制台与账单页")),
        OutboundHost(host: "dashboard.clerk.com", purpose: L("Clerk 控制台与账单页")),
        OutboundHost(host: "sentry.io", purpose: L("Sentry 用量 API、控制台与账单页")),
        OutboundHost(host: "api.vultr.com", purpose: L("Vultr 账单 API")),
        OutboundHost(host: "my.vultr.com", purpose: L("Vultr 控制台与账单页")),
        OutboundHost(host: "api.fastly.com", purpose: L("Fastly 账单 API")),
        OutboundHost(host: "manage.fastly.com", purpose: L("Fastly 控制台与账单页")),
        OutboundHost(host: "admin-api.exa.ai", purpose: L("Exa 账单 API")),
        OutboundHost(host: "dashboard.exa.ai", purpose: L("Exa 控制台与账单页")),
        OutboundHost(host: "cloud.mongodb.com", purpose: L("MongoDB Atlas 账单 API、控制台与账单页")),
        OutboundHost(host: "login.microsoftonline.com", purpose: L("Azure 服务主体换取访问令牌")),
        OutboundHost(host: "management.azure.com", purpose: L("Azure 成本管理 API")),
        OutboundHost(host: "portal.azure.com", purpose: L("Azure 控制台与账单页")),
        OutboundHost(host: "api.polar.sh", purpose: L("Polar 账单 API")),
        OutboundHost(host: "polar.sh", purpose: L("Polar 控制台与账单页")),
        OutboundHost(host: "api.heroku.com", purpose: L("Heroku 账单 API")),
        OutboundHost(host: "dashboard.heroku.com", purpose: L("Heroku 控制台与账单页")),
        OutboundHost(host: "api.revenuecat.com", purpose: L("RevenueCat 指标 API")),
        OutboundHost(host: "app.revenuecat.com", purpose: L("RevenueCat 控制台与账单页")),
        OutboundHost(host: "gitlab.com", purpose: L("GitLab 控制台与用量配额页")),
        OutboundHost(host: "customers.gitlab.com", purpose: L("GitLab Customers Portal 账单页")),
        OutboundHost(host: "api.cloud.qdrant.io", purpose: L("Qdrant Cloud 账单 API")),
        OutboundHost(host: "cloud.qdrant.io", purpose: L("Qdrant Cloud 控制台与账单页")),
        OutboundHost(host: "dashboard.render.com", purpose: L("Render 控制台与账单页")),
        OutboundHost(host: "expo.dev", purpose: L("Expo 控制台与账单页")),
        OutboundHost(host: "api.mistral.ai", purpose: L("Mistral 账单 API")),
        OutboundHost(host: "admin.mistral.ai", purpose: L("Mistral 控制台与账单页")),
        OutboundHost(host: "backoffice.mistral.ai", purpose: L("Mistral Admin API 密钥页")),
        OutboundHost(host: "api.fireworks.ai", purpose: L("Fireworks 账单 API")),
        OutboundHost(host: "app.fireworks.ai", purpose: L("Fireworks 控制台与账单页")),
        OutboundHost(host: "api.fal.ai", purpose: L("fal.ai 账单 API")),
        OutboundHost(host: "fal.ai", purpose: L("fal.ai 控制台与账单页")),
        OutboundHost(host: "huggingface.co", purpose: L("Hugging Face 账单 API、控制台与账单页")),
        OutboundHost(host: "api.turso.tech", purpose: L("Turso 账单 API")),
        OutboundHost(host: "app.turso.tech", purpose: L("Turso 控制台与账单页")),
        OutboundHost(host: "docs.turso.tech", purpose: L("Turso API Token 文档")),
        OutboundHost(host: "api.baseten.co", purpose: L("Baseten 账单 API")),
        OutboundHost(host: "app.baseten.co", purpose: L("Baseten 控制台与账单页")),
        OutboundHost(host: "docs.baseten.co", purpose: L("Baseten API Key 文档")),
        OutboundHost(host: "api.clickhouse.cloud", purpose: L("ClickHouse Cloud 账单 API")),
        OutboundHost(host: "console.clickhouse.cloud", purpose: L("ClickHouse Cloud 控制台与账单页")),
        OutboundHost(host: "clickhouse.com", purpose: L("ClickHouse Cloud API 密钥文档")),
        OutboundHost(host: "api.linode.com", purpose: L("Linode 账单 API")),
        OutboundHost(host: "cloud.linode.com", purpose: L("Linode 控制台与账单页")),
        OutboundHost(host: "api.runpod.io", purpose: L("RunPod 账单 API")),
        OutboundHost(host: "www.runpod.io", purpose: L("RunPod 控制台与账单页")),
        OutboundHost(host: "api.deepgram.com", purpose: L("Deepgram 账单 API")),
        OutboundHost(host: "console.deepgram.com", purpose: L("Deepgram 控制台与账单页")),
        OutboundHost(host: "developers.deepgram.com", purpose: L("Deepgram API Key 文档")),
        OutboundHost(host: "api.scaleway.com", purpose: L("Scaleway 账单 API")),
        OutboundHost(host: "console.scaleway.com", purpose: L("Scaleway 控制台与账单页")),
        OutboundHost(host: "api.bunny.net", purpose: L("bunny.net 账单 API")),
        OutboundHost(host: "dash.bunny.net", purpose: L("bunny.net 控制台与账单页")),
        OutboundHost(host: "docs.bunny.net", purpose: L("bunny.net API Key 文档")),
        OutboundHost(host: "grafana.com", purpose: L("Grafana Cloud 账单 API、控制台与文档")),
        OutboundHost(host: "cloud.elastic.co", purpose: L("Elastic Cloud 账单 API、控制台与账单页")),
        OutboundHost(host: "www.elastic.co", purpose: L("Elastic Cloud API 密钥文档")),
        OutboundHost(host: "api.datadoghq.com", purpose: L("Datadog 账单 API（US1）")),
        OutboundHost(host: "api.datadoghq.eu", purpose: L("Datadog 账单 API（EU）")),
        OutboundHost(host: "api.us3.datadoghq.com", purpose: L("Datadog 账单 API（US3）")),
        OutboundHost(host: "api.us5.datadoghq.com", purpose: L("Datadog 账单 API（US5）")),
        OutboundHost(host: "api.ap1.datadoghq.com", purpose: L("Datadog 账单 API（AP1）")),
        OutboundHost(host: "api.ap2.datadoghq.com", purpose: L("Datadog 账单 API（AP2）")),
        OutboundHost(host: "api.uk1.datadoghq.com", purpose: L("Datadog 账单 API（UK1）")),
        OutboundHost(host: "app.datadoghq.com", purpose: L("Datadog 控制台与账单页")),
        OutboundHost(host: "api.novita.ai", purpose: L("Novita 账单 API")),
        OutboundHost(host: "novita.ai", purpose: L("Novita 控制台与账单页")),
        OutboundHost(host: "api.apify.com", purpose: L("Apify 账单 API")),
        OutboundHost(host: "console.apify.com", purpose: L("Apify 控制台与账单页")),
        OutboundHost(host: "api.tavily.com", purpose: L("Tavily 用量 API")),
        OutboundHost(host: "app.tavily.com", purpose: L("Tavily 控制台与账单页")),
        OutboundHost(host: "docs.tavily.com", purpose: L("Tavily API Key 文档")),
        OutboundHost(host: "api.deepinfra.com", purpose: L("DeepInfra 账单 API")),
        OutboundHost(host: "deepinfra.com", purpose: L("DeepInfra 控制台与账单页")),
        OutboundHost(host: "docs.deepinfra.com", purpose: L("DeepInfra API Key 文档")),
        OutboundHost(host: "console.vast.ai", purpose: L("Vast.ai 账单 API")),
        OutboundHost(host: "cloud.vast.ai", purpose: L("Vast.ai 控制台与账单页")),
        OutboundHost(host: "api.firecrawl.dev", purpose: L("Firecrawl 用量 API")),
        OutboundHost(host: "www.firecrawl.dev", purpose: L("Firecrawl 控制台与账单页")),
        OutboundHost(host: "cockroachlabs.cloud", purpose: L("CockroachDB Cloud 账单 API、控制台与账单页")),
        OutboundHost(host: "cloud.typesense.org", purpose: L("Typesense Cloud 账单 API、控制台与账单页")),
        OutboundHost(host: "typesense.org", purpose: L("Typesense Cloud API 密钥文档")),
        OutboundHost(host: "api.aiven.io", purpose: L("Aiven 账单 API")),
        OutboundHost(host: "console.aiven.io", purpose: L("Aiven 控制台与账单页")),
        OutboundHost(host: "aiven.io", purpose: L("Aiven 签发 token 文档")),
        OutboundHost(host: "api.siliconflow.cn", purpose: L("SiliconFlow 账单 API")),
        OutboundHost(host: "cloud.siliconflow.cn", purpose: L("SiliconFlow 控制台与账单页")),
        OutboundHost(host: "api.aimlapi.com", purpose: L("AI/ML API 账单 API")),
        OutboundHost(host: "aimlapi.com", purpose: L("AI/ML API 控制台与账单页")),
        OutboundHost(host: "api.stepfun.com", purpose: L("StepFun (China) 账单 API")),
        OutboundHost(host: "platform.stepfun.com", purpose: L("StepFun (China) 控制台与账单页")),
        OutboundHost(host: "api.stepfun.ai", purpose: L("StepFun (Overseas) 账单 API")),
        OutboundHost(host: "platform.stepfun.ai", purpose: L("StepFun (Overseas) 控制台与账单页")),
        OutboundHost(host: "api.telnyx.com", purpose: L("Telnyx 账单 API")),
        OutboundHost(host: "portal.telnyx.com", purpose: L("Telnyx 控制台与账单页")),
        OutboundHost(host: "api.skysql.com", purpose: L("MariaDB Cloud 账单 API")),
        OutboundHost(host: "app.skysql.com", purpose: L("MariaDB Cloud 控制台与账单页")),
        OutboundHost(host: "api.ionos.com", purpose: L("IONOS Cloud 账单 API")),
        OutboundHost(host: "dcd.ionos.com", purpose: L("IONOS Cloud 控制台与账单页")),
        OutboundHost(host: "docs.ionos.com", purpose: L("IONOS Cloud 签发 token 文档")),
        OutboundHost(host: "api.upcloud.com", purpose: L("UpCloud 账单 API")),
        OutboundHost(host: "hub.upcloud.com", purpose: L("UpCloud 控制台与账单页")),
        OutboundHost(host: "upcloud.com", purpose: L("UpCloud 签发 token 文档")),
        OutboundHost(host: "api.confluent.cloud", purpose: L("Confluent Cloud 账单 API")),
        OutboundHost(host: "confluent.cloud", purpose: L("Confluent Cloud 控制台与账单页")),
        OutboundHost(host: "rest.nexmo.com", purpose: L("Vonage 账单 API")),
        OutboundHost(host: "dashboard.nexmo.com", purpose: L("Vonage 控制台与账单页")),
        OutboundHost(host: "api.plivo.com", purpose: L("Plivo 账单 API")),
        OutboundHost(host: "console.plivo.com", purpose: L("Plivo 控制台与账单页")),
        OutboundHost(host: "rest.messagebird.com", purpose: L("MessageBird 账单 API")),
        OutboundHost(host: "dashboard.messagebird.com", purpose: L("MessageBird 控制台与账单页")),
        OutboundHost(host: "iam.cloud.ibm.com", purpose: L("IBM Cloud 换取访问令牌")),
        OutboundHost(host: "billing.cloud.ibm.com", purpose: L("IBM Cloud 账单 API")),
        OutboundHost(host: "cloud.ibm.com", purpose: L("IBM Cloud 控制台与账单页")),
        OutboundHost(host: "rest.clicksend.com", purpose: L("ClickSend 账单 API")),
        OutboundHost(host: "dashboard.clicksend.com", purpose: L("ClickSend 控制台与账单页")),
        OutboundHost(host: "developers.clicksend.com", purpose: L("ClickSend API 文档")),
        OutboundHost(host: "api.infobip.com", purpose: L("Infobip 账单 API")),
        OutboundHost(host: "portal.infobip.com", purpose: L("Infobip 控制台与账单页")),
        OutboundHost(host: "www.infobip.com", purpose: L("Infobip 签发 API key 文档")),
        OutboundHost(host: "rest.textmagic.com", purpose: L("Textmagic 账单 API")),
        OutboundHost(host: "app.textmagic.com", purpose: L("Textmagic 控制台与账单页")),
        OutboundHost(host: "betterstack.com", purpose: L("Better Stack 账单 API、控制台与文档")),
        OutboundHost(host: "api.easypost.com", purpose: L("EasyPost 账单 API")),
        OutboundHost(host: "app.easypost.com", purpose: L("EasyPost 控制台与账单页")),
        OutboundHost(host: "docs.easypost.com", purpose: L("EasyPost 认证文档")),
        OutboundHost(host: "api2.transloadit.com", purpose: L("Transloadit 账单 API")),
        OutboundHost(host: "transloadit.com", purpose: L("Transloadit 控制台与认证文档")),
        OutboundHost(host: "v2.api2pdf.com", purpose: L("Api2Pdf 账单 API")),
        OutboundHost(host: "portal.api2pdf.com", purpose: L("Api2Pdf 控制台与账单页")),
        OutboundHost(host: "www.api2pdf.com", purpose: L("Api2Pdf 文档站点")),
        OutboundHost(host: "api.hetrixtools.com", purpose: L("HetrixTools 账单 API")),
        OutboundHost(host: "hetrixtools.com", purpose: L("HetrixTools 控制台与文档")),
        OutboundHost(host: "docs.hetrixtools.com", purpose: L("HetrixTools API 文档")),
        OutboundHost(host: "api.shipengine.com", purpose: L("ShipStation / ShipEngine 账单 API")),
        OutboundHost(host: "www.shipstation.com", purpose: L("ShipStation 控制台与账单页")),
        OutboundHost(host: "docs.shipstation.com", purpose: L("ShipStation API 文档")),
        OutboundHost(host: "api.thanks.io", purpose: L("thanks.io 账单 API")),
        OutboundHost(host: "www.thanks.io", purpose: L("thanks.io 控制台与账单页")),
        OutboundHost(host: "docs.thanks.io", purpose: L("thanks.io 认证文档")),
        OutboundHost(host: "rest.click2mail.com", purpose: L("Click2Mail 账单 API")),
        OutboundHost(host: "www.click2mail.com", purpose: L("Click2Mail 控制台与账单页")),
        OutboundHost(host: "developers.click2mail.com", purpose: L("Click2Mail API 文档")),
        OutboundHost(host: "order.gelatoapis.com", purpose: L("Gelato 账单 API")),
        OutboundHost(host: "dashboard.gelato.com", purpose: L("Gelato 控制台与账单页")),
        OutboundHost(host: "api.prodigi.com", purpose: L("Prodigi 账单 API")),
        OutboundHost(host: "www.prodigi.com", purpose: L("Prodigi 控制台与文档")),
        OutboundHost(host: "api.qiniu.com", purpose: L("七牛云账单 API")),
        OutboundHost(host: "portal.qiniu.com", purpose: L("七牛云控制台与账单页")),
        OutboundHost(host: "developer.qiniu.com", purpose: L("七牛云 AccessKey 文档")),
        OutboundHost(host: "api.mysendingbox.fr", purpose: L("MySendingBox 账单 API")),
        OutboundHost(host: "www.mysendingbox.fr", purpose: L("MySendingBox 控制台与账单页")),
        OutboundHost(host: "docs.mysendingbox.fr", purpose: L("MySendingBox API 文档")),
        OutboundHost(host: "api-us1.stannp.com", purpose: L("Stannp 账单 API")),
        OutboundHost(host: "www.stannp.com", purpose: L("Stannp 控制台与文档")),
        OutboundHost(host: "api.phaxio.com", purpose: L("Phaxio 账单 API")),
        OutboundHost(host: "www.phaxio.com", purpose: L("Phaxio 控制台与文档")),
        OutboundHost(host: "api.porkbun.com", purpose: L("Porkbun 账单 API")),
        OutboundHost(host: "porkbun.com", purpose: L("Porkbun 控制台与文档")),
        OutboundHost(host: "api.namecheap.com", purpose: L("Namecheap 账单 API")),
        OutboundHost(host: "www.namecheap.com", purpose: L("Namecheap 控制台与 API 文档")),
        OutboundHost(host: "api.gandi.net", purpose: L("Gandi 账单 API 与认证文档")),
        OutboundHost(host: "admin.gandi.net", purpose: L("Gandi 控制台与账单页")),
        OutboundHost(host: "api.goshippo.com", purpose: L("Shippo 账单 API")),
        OutboundHost(host: "apps.goshippo.com", purpose: L("Shippo 控制台")),
        OutboundHost(host: "docs.goshippo.com", purpose: L("Shippo 认证文档")),
        OutboundHost(host: "api.printful.com", purpose: L("Printful 账单 API")),
        OutboundHost(host: "www.printful.com", purpose: L("Printful 控制台与文档")),
        OutboundHost(host: "api.print.io", purpose: L("Gooten 账单 API")),
        OutboundHost(host: "www.gooten.com", purpose: L("Gooten 控制台与文档")),
        OutboundHost(host: "public-api.easyship.com", purpose: L("Easyship 账单 API")),
        OutboundHost(host: "app.easyship.com", purpose: L("Easyship 控制台")),
        OutboundHost(host: "developers.easyship.com", purpose: L("Easyship API 文档")),
        OutboundHost(host: "bss-intl.myhuaweicloud.com", purpose: L("Huawei Cloud 国际站账单 API")),
        OutboundHost(host: "account-intl.myhuaweicloud.com", purpose: L("Huawei Cloud 国际站控制台")),
        OutboundHost(host: "support.huaweicloud.com", purpose: L("Huawei Cloud API 文档")),
        OutboundHost(host: "api.nexmo.com", purpose: L("Vonage Reports API")),
        OutboundHost(host: "console.cloud.google.com", purpose: L("Google Cloud 控制台与账单页")),
        OutboundHost(host: "my.slack.com", purpose: L("Slack 控制台与账单页")),
        OutboundHost(host: "slack.com", purpose: L("Slack 账单帮助文档")),
        OutboundHost(host: "www.notion.so", purpose: L("Notion 控制台与账单页")),
        OutboundHost(host: "www.figma.com", purpose: L("Figma 控制台与账单页")),
        OutboundHost(host: "help.figma.com", purpose: L("Figma 账单帮助文档")),
        OutboundHost(host: "supabase.com", purpose: L("Supabase 控制台与账单页")),
        OutboundHost(host: "linear.app", purpose: L("Linear 控制台与账单页")),
        OutboundHost(host: "app.pulumi.com", purpose: L("Pulumi Cloud 控制台与账单页")),
        OutboundHost(host: "www.pulumi.com", purpose: L("Pulumi Cloud 签发 token 文档")),
        OutboundHost(host: "api.active24.com", purpose: L("Active24 账单 API")),
        OutboundHost(host: "www.active24.com", purpose: L("Active24 控制台与文档")),
        OutboundHost(host: "api.azion.com", purpose: L("Azion GraphQL 账单 API")),
        OutboundHost(host: "console.azion.com", purpose: L("Azion 控制台与账单页")),
        OutboundHost(host: "www.azion.com", purpose: L("Azion API 文档")),
        OutboundHost(host: "ops.elastx.cloud", purpose: L("Elastx CloudKitty 账单 API")),
        OutboundHost(host: "docs.elastx.cloud", purpose: L("Elastx 账单文档")),
        OutboundHost(host: "api.warpstream.com", purpose: L("WarpStream 发票 API")),
        OutboundHost(host: "console.warpstream.com", purpose: L("WarpStream 控制台")),
        OutboundHost(host: "docs.warpstream.com", purpose: L("WarpStream API 文档")),
        OutboundHost(host: "api.neo4j.io", purpose: L("Neo4j Aura 账单 API")),
        OutboundHost(host: "console.neo4j.io", purpose: L("Neo4j Aura 控制台")),
        OutboundHost(host: "neo4j.com", purpose: L("Neo4j Aura API 文档")),
        OutboundHost(host: "www.digicert.com", purpose: L("DigiCert CertCentral 财务 API 与控制台")),
        OutboundHost(host: "dev.digicert.com", purpose: L("DigiCert API 文档")),
        OutboundHost(host: "a.klaviyo.com", purpose: L("Klaviyo billing-usage API")),
        OutboundHost(host: "www.klaviyo.com", purpose: L("Klaviyo 控制台与账单页")),
        OutboundHost(host: "developers.klaviyo.com", purpose: L("Klaviyo API 文档")),
        OutboundHost(host: "api.letsdeel.com", purpose: L("Deel 平台费发票 API")),
        OutboundHost(host: "app.deel.com", purpose: L("Deel 控制台")),
        OutboundHost(host: "developer.deel.com", purpose: L("Deel API 文档")),
        OutboundHost(host: "gateway.remote.com", purpose: L("Remote.com 账单单据 API")),
        OutboundHost(host: "employ.remote.com", purpose: L("Remote.com 控制台")),
        OutboundHost(host: "developer.remote.com", purpose: L("Remote.com API 文档")),
        OutboundHost(host: "api.oysterhr.com", purpose: L("Oyster HR 发票 API")),
        OutboundHost(host: "app.oysterhr.com", purpose: L("Oyster 控制台")),
        OutboundHost(host: "docs.oysterhr.com", purpose: L("Oyster API 文档")),
        OutboundHost(host: "api.northflank.com", purpose: L("Northflank 账单 API")),
        OutboundHost(host: "api.gcore.com", purpose: L("Gcore 账单 API")),
        OutboundHost(host: "api.eu-west-2.outscale.com", purpose: L("3DS OUTSCALE 账单 API（eu-west-2）")),
        OutboundHost(host: "api.us-east-2.outscale.com", purpose: L("3DS OUTSCALE 账单 API（us-east-2）")),
        OutboundHost(host: "api.us-west-1.outscale.com", purpose: L("3DS OUTSCALE 账单 API（us-west-1）")),
        OutboundHost(host: "api.ap-northeast-1.outscale.com", purpose: L("3DS OUTSCALE 账单 API（ap-northeast-1）")),
        OutboundHost(host: "api.cloudgouv-eu-west-1.outscale.com", purpose: L("3DS OUTSCALE SecNumCloud 账单 API")),
        OutboundHost(host: "cockpit.outscale.com", purpose: L("3DS OUTSCALE 控制台")),
        OutboundHost(host: "docs.outscale.com", purpose: L("3DS OUTSCALE API 文档")),
        OutboundHost(host: "api.orange.com", purpose: L("Orange Cloud Avenue / Flexible Engine 账单 API")),
        OutboundHost(host: "cloud.orange-business.com", purpose: L("Orange Cloud 控制台与文档")),
        OutboundHost(host: "api.gridscale.io", purpose: L("gridscale Public API")),
        OutboundHost(host: "my.gridscale.io", purpose: L("gridscale 控制台")),
        OutboundHost(host: "gridscale.io", purpose: L("gridscale 文档")),
        OutboundHost(host: "billing.api.rackspacecloud.com", purpose: L("Rackspace Billing API")),
        OutboundHost(host: "identity.api.rackspacecloud.com", purpose: L("Rackspace Identity 鉴权")),
        OutboundHost(host: "accounts.rackspace.com", purpose: L("Rackspace 控制台")),
        OutboundHost(host: "docs.rackspace.com", purpose: L("Rackspace API 文档")),
        OutboundHost(host: "platform.claude.com", purpose: L("Anthropic Claude 平台文档")),
        OutboundHost(host: "api.dev.pika.art", purpose: L("Pika 账单 API")),
        OutboundHost(host: "dev.pika.art", purpose: L("Pika OpenAPI / 控制台")),
        OutboundHost(host: "api.hedra.com", purpose: L("Hedra 用量 API")),
        OutboundHost(host: "www.hedra.com", purpose: L("Hedra 文档与控制台")),
        OutboundHost(host: "billing.tidbapi.com", purpose: L("TiDB Cloud 账单 API")),
        OutboundHost(host: "tidbcloud.com", purpose: L("TiDB Cloud 控制台")),
        OutboundHost(host: "docs.pingcap.com", purpose: L("TiDB Cloud API 文档")),
        OutboundHost(host: "infrahub-api.nexgencloud.com", purpose: L("Hyperstack 账单 API")),
        OutboundHost(host: "console.hyperstack.cloud", purpose: L("Hyperstack 控制台")),
        OutboundHost(host: "docs.hyperstack.cloud", purpose: L("Hyperstack API 文档")),
        OutboundHost(host: "cloud.hostup.se", purpose: L("HostUp 账单 API 与控制台")),
        OutboundHost(host: "developer.hostup.se", purpose: L("HostUp API 文档")),
        OutboundHost(host: "hostup.se", purpose: L("HostUp 官网")),
        OutboundHost(host: "api.memset.com", purpose: L("Memset 账单 API")),
        OutboundHost(host: "www.memset.com", purpose: L("Memset 控制台与 API 文档")),
        OutboundHost(host: "api.mittwald.de", purpose: L("mittwald 账单 API")),
        OutboundHost(host: "my.mittwald.de", purpose: L("mittwald 控制台")),
        OutboundHost(host: "developer.mittwald.de", purpose: L("mittwald API 文档")),
        OutboundHost(host: "api.soracom.io", purpose: L("Soracom 日本覆盖账单 API")),
        OutboundHost(host: "g.api.soracom.io", purpose: L("Soracom 全球覆盖账单 API")),
        OutboundHost(host: "console.soracom.io", purpose: L("Soracom 控制台")),
        OutboundHost(host: "developers.soracom.io", purpose: L("Soracom API 文档")),
        OutboundHost(host: "starlink.com", purpose: L("Starlink 账单 API 与控制台")),
        OutboundHost(host: "www.starlink.com", purpose: L("Starlink 账户页")),
        OutboundHost(host: "starlink.readme.io", purpose: L("Starlink API 文档")),
        OutboundHost(host: "api.tibber.com", purpose: L("Tibber GraphQL API")),
        OutboundHost(host: "tibber.com", purpose: L("Tibber 控制台")),
        OutboundHost(host: "developer.tibber.com", purpose: L("Tibber 开发者文档")),
        OutboundHost(host: "api.1nce.com", purpose: L("1NCE Management API")),
        OutboundHost(host: "portal.1nce.com", purpose: L("1NCE 控制台")),
        OutboundHost(host: "help.1nce.com", purpose: L("1NCE API 文档")),
        OutboundHost(host: "api.octopus.energy", purpose: L("Octopus Energy GraphQL API")),
        OutboundHost(host: "octopus.energy", purpose: L("Octopus Energy 控制台")),
        OutboundHost(host: "developer.octopus.energy", purpose: L("Octopus Energy API 文档")),
        OutboundHost(host: "api.pge.com", purpose: L("PG&E Share My Data / Green Button API")),
        OutboundHost(host: "www.pge.com", purpose: L("PG&E 控制台与文档")),
        OutboundHost(host: "sharemydata.pge.com", purpose: L("PG&E Share My Data 注册")),
        OutboundHost(host: "api.coned.com", purpose: L("Con Edison / ORU Share My Data Green Button API")),
        OutboundHost(host: "www.coned.com", purpose: L("Con Edison 控制台与 Share My Data 文档")),
        OutboundHost(host: "api.dynatrace.com", purpose: L("Dynatrace Platform Subscription 账单 API")),
        OutboundHost(host: "sso.dynatrace.com", purpose: L("Dynatrace Account SSO OAuth")),
        OutboundHost(host: "myaccount.dynatrace.com", purpose: L("Dynatrace 账户控制台")),
        OutboundHost(host: "docs.dynatrace.com", purpose: L("Dynatrace API 文档")),
        OutboundHost(host: "api.zoom.us", purpose: L("Zoom Billing API")),
        OutboundHost(host: "zoom.us", purpose: L("Zoom 控制台与账单页")),
        OutboundHost(host: "developers.zoom.us", purpose: L("Zoom API 文档")),
        OutboundHost(host: "api.name.com", purpose: L("Name.com Core API")),
        OutboundHost(host: "www.name.com", purpose: L("Name.com 控制台")),
        OutboundHost(host: "docs.name.com", purpose: L("Name.com API 文档")),
        OutboundHost(host: "eu.api.ovh.com", purpose: L("OVHcloud APIv6")),
        OutboundHost(host: "api.ovh.com", purpose: L("OVHcloud API 控制台")),
        OutboundHost(host: "www.ovhcloud.com", purpose: L("OVHcloud 控制台")),
        OutboundHost(host: "secure.sakura.ad.jp", purpose: L("さくらのクラウド API")),
        OutboundHost(host: "manual.sakura.ad.jp", purpose: L("さくらクラウド API マニュアル")),
        OutboundHost(host: "luna.akamaiapis.net", purpose: L("Akamai EdgeGrid / Invoicing API")),
        OutboundHost(host: "techdocs.akamai.com", purpose: L("Akamai Invoicing 文档")),
        OutboundHost(host: "control.akamai.com", purpose: L("Akamai Control Center")),
        OutboundHost(host: "billing.hostens.com", purpose: L("Hostens 账单 API")),
        OutboundHost(host: "api.binarylane.com.au", purpose: L("BinaryLane 账单 API")),
        OutboundHost(host: "api.tierpoint.com", purpose: L("TierPoint Metallic 用量 API")),
        OutboundHost(host: "api.postman.com", purpose: L("Postman 账单 API")),
        OutboundHost(host: "api.eu.postman.com", purpose: L("Postman 欧盟账单 API")),
        OutboundHost(host: "api.sbgenomics.com", purpose: L("Seven Bridges 账单 API")),
        OutboundHost(host: "eu-api.sbgenomics.com", purpose: L("Seven Bridges 欧盟账单 API")),
        OutboundHost(host: "docs.sevenbridges.com", purpose: L("Seven Bridges API 文档")),
        OutboundHost(host: "api.cm.com", purpose: L("CM.com 交易账单 API")),
        OutboundHost(host: "developers.cm.com", purpose: L("CM.com API 文档")),
        OutboundHost(host: "api.shipbob.com", purpose: L("ShipBob 账单 API")),
        OutboundHost(host: "web.shipbob.com", purpose: L("ShipBob 控制台")),
        OutboundHost(host: "developer.shipbob.com", purpose: L("ShipBob Billing 文档")),
        OutboundHost(host: "api.mikrocloud.com", purpose: L("MikroCloud 账单 API")),
        OutboundHost(host: "docs.mikrocloud.com", purpose: L("MikroCloud API 文档")),
        OutboundHost(host: "mikrocloud.com", purpose: L("MikroCloud 控制台")),
        OutboundHost(host: "api.leaseweb.com", purpose: L("Leaseweb 账单 API")),
        OutboundHost(host: "secure.leaseweb.com", purpose: L("Leaseweb 控制台")),
        OutboundHost(host: "developer.leaseweb.com", purpose: L("Leaseweb Invoice API 文档")),
        OutboundHost(host: "api.qovery.com", purpose: L("Qovery 账单 API")),
        OutboundHost(host: "console.qovery.com", purpose: L("Qovery 控制台")),
        OutboundHost(host: "www.qovery.com", purpose: L("Qovery API 文档")),
        OutboundHost(host: "api.phoenixnap.com", purpose: L("phoenixNAP Invoicing API")),
        OutboundHost(host: "auth.phoenixnap.com", purpose: L("phoenixNAP BMC OAuth")),
        OutboundHost(host: "bmc.phoenixnap.com", purpose: L("phoenixNAP BMC 控制台")),
        OutboundHost(host: "developers.phoenixnap.com", purpose: L("phoenixNAP API 文档")),
        OutboundHost(host: "api.magalu.cloud", purpose: L("Magalu Cloud 消费 API")),
        OutboundHost(host: "console.magalu.cloud", purpose: L("Magalu Cloud 控制台")),
        OutboundHost(host: "docs.magalu.cloud", purpose: L("Magalu Cloud API 文档")),
        OutboundHost(host: "api.transip.nl", purpose: L("TransIP 账单 API")),
        OutboundHost(host: "www.transip.nl", purpose: L("TransIP 控制台")),
        OutboundHost(host: "api.servers.com", purpose: L("Servers.com 账单 API")),
        OutboundHost(host: "portal.servers.com", purpose: L("Servers.com 控制台")),
        OutboundHost(host: "www.servers.com", purpose: L("Servers.com Invoice API 文档")),
        OutboundHost(host: "api.flexport.com", purpose: L("Flexport 账单 API")),
        OutboundHost(host: "app.flexport.com", purpose: L("Flexport 控制台")),
        OutboundHost(host: "developers.flexport.com", purpose: L("Flexport Invoices 文档")),
        OutboundHost(host: "api.i3d.net", purpose: L("i3D.net 账单 API")),
        OutboundHost(host: "www.i3d.net", purpose: L("i3D.net 控制台")),
        OutboundHost(host: "docs.i3d.net", purpose: L("i3D.net Billing 文档")),
        OutboundHost(host: "api.datapacket.com", purpose: L("DataPacket GraphQL 账单 API")),
        OutboundHost(host: "www.datapacket.com", purpose: L("DataPacket 控制台")),
        OutboundHost(host: "rest.compute.cudo.org", purpose: L("CUDO Compute 账单 API")),
        OutboundHost(host: "www.cudocompute.com", purpose: L("CUDO Compute 控制台")),
        OutboundHost(host: "docs.cudocompute.com", purpose: L("CUDO Compute Billing 文档")),
        OutboundHost(host: "api.shipwell.com", purpose: L("Shipwell 货运发票 API")),
        OutboundHost(host: "sandbox-api.shipwell.com", purpose: L("Shipwell 沙箱 API")),
        OutboundHost(host: "shipwell.com", purpose: L("Shipwell 控制台")),
        OutboundHost(host: "docs.shipwell.com", purpose: L("Shipwell Settlements 文档")),
        OutboundHost(host: "api.ocamba.com", purpose: L("Ocamba 账单 API")),
        OutboundHost(host: "docs.ocamba.com", purpose: L("Ocamba Invoices 文档")),
        OutboundHost(host: "api.inference.sh", purpose: L("inference.sh 账单 API")),
        OutboundHost(host: "inference.sh", purpose: L("inference.sh 控制台与文档")),
        OutboundHost(host: "api.voltview.co.uk", purpose: L("VoltView 账单 API")),
        OutboundHost(host: "docs.voltview.co.uk", purpose: L("VoltView Invoices 文档")),
        OutboundHost(host: "api-bridge.clever-cloud.com", purpose: L("Clever Cloud Auth Bridge 账单 API")),
        OutboundHost(host: "api.clever-cloud.com", purpose: L("Clever Cloud API")),
        OutboundHost(host: "console.clever-cloud.com", purpose: L("Clever Cloud 控制台")),
        OutboundHost(host: "www.clever.cloud", purpose: L("Clever Cloud API 文档")),
        OutboundHost(host: "utilityapi.com", purpose: L("UtilityAPI 账单 API 与控制台")),
        OutboundHost(host: "api.dnsimple.com", purpose: L("DNSimple 账单 API")),
        OutboundHost(host: "dnsimple.com", purpose: L("DNSimple 控制台")),
        OutboundHost(host: "developer.dnsimple.com", purpose: L("DNSimple Billing Charges 文档")),
        OutboundHost(host: "api.latitude.sh", purpose: L("Latitude.sh 账单 API")),
        OutboundHost(host: "www.latitude.sh", purpose: L("Latitude.sh 控制台与文档")),
        OutboundHost(host: "api.yoursrs.com", purpose: L("Realtime Register 账单 API")),
        OutboundHost(host: "api.yoursrs-ote.com", purpose: L("Realtime Register OTE API")),
        OutboundHost(host: "api.pdfshift.io", purpose: L("PDFShift 账单 API")),
        OutboundHost(host: "admin-api.alchemy.com", purpose: L("Alchemy Admin 用量 API")),
        OutboundHost(host: "dashboard.alchemy.com", purpose: L("Alchemy 控制台")),
        OutboundHost(host: "www.alchemy.com", purpose: L("Alchemy 文档")),
        OutboundHost(host: "api.friendli.ai", purpose: L("FriendliAI 费用 API")),
        OutboundHost(host: "friendli.ai", purpose: L("FriendliAI 控制台与文档")),
        OutboundHost(host: "api.mixpeek.com", purpose: L("Mixpeek 账单 API")),
        OutboundHost(host: "mixpeek.com", purpose: L("Mixpeek 控制台")),
        OutboundHost(host: "docs.mixpeek.com", purpose: L("Mixpeek 文档")),
        OutboundHost(host: "app.typebot.io", purpose: L("Typebot 账单 API")),
        OutboundHost(host: "app.typebot.com", purpose: L("Typebot 备用 Host")),
        OutboundHost(host: "docs.typebot.com", purpose: L("Typebot 文档")),
        OutboundHost(host: "api.botpress.cloud", purpose: L("Botpress Admin 账单 API")),
        OutboundHost(host: "viber.botpress.cloud", purpose: L("Botpress 控制台")),
        OutboundHost(host: "www.botpress.com", purpose: L("Botpress 文档")),
        OutboundHost(host: "api.vps.net", purpose: L("VPS.NET 账单 API")),
        OutboundHost(host: "api.seeweb.it", purpose: L("Seeweb ECS 账单 API")),
        OutboundHost(host: "www.seeweb.it", purpose: L("Seeweb 控制台")),
        OutboundHost(host: "docs.seeweb.it", purpose: L("Seeweb 文档")),
        OutboundHost(host: "api.parasail.io", purpose: L("Parasail 账单 API")),
        OutboundHost(host: "www.parasail.io", purpose: L("Parasail 控制台")),
        OutboundHost(host: "docs.parasail.io", purpose: L("Parasail 文档")),
        OutboundHost(host: "www.mybring.com", purpose: L("Bring 发票 API")),
        OutboundHost(host: "developer.bring.com", purpose: L("Bring 文档")),
        OutboundHost(host: "api.armadadelivery.com", purpose: L("Armada 发票 API")),
        OutboundHost(host: "docs.armadadelivery.com", purpose: L("Armada 文档")),
        OutboundHost(host: "www.armadadelivery.com", purpose: L("Armada 控制台")),
        OutboundHost(host: "api.mollie.com", purpose: L("Mollie 发票 API")),
        OutboundHost(host: "my.mollie.com", purpose: L("Mollie 控制台")),
        OutboundHost(host: "docs.mollie.com", purpose: L("Mollie 文档")),
        OutboundHost(host: "api.checkout.com", purpose: L("Checkout.com 对账单 API")),
        OutboundHost(host: "dashboard.checkout.com", purpose: L("Checkout.com 控制台")),
        OutboundHost(host: "checkoutdocs.readme.io", purpose: L("Checkout.com 文档")),
        OutboundHost(host: "api.printify.com", purpose: L("Printify 订单 API")),
        OutboundHost(host: "printify.com", purpose: L("Printify 控制台")),
        OutboundHost(host: "developers.printify.com", purpose: L("Printify 文档")),
        OutboundHost(host: "api.teelaunch.com", purpose: L("teelaunch 支付历史 API")),
        OutboundHost(host: "teelaunch.com", purpose: L("teelaunch 控制台")),
        OutboundHost(host: "api-m.paypal.com", purpose: L("PayPal 交易手续费 API")),
        OutboundHost(host: "www.paypal.com", purpose: L("PayPal 控制台")),
        OutboundHost(host: "developer.paypal.com", purpose: L("PayPal 文档")),
        OutboundHost(host: "api.paystack.co", purpose: L("Paystack 交易手续费 API")),
        OutboundHost(host: "dashboard.paystack.com", purpose: L("Paystack 控制台")),
        OutboundHost(host: "paystack.com", purpose: L("Paystack 文档")),
        OutboundHost(host: "api.flutterwave.com", purpose: L("Flutterwave 交易手续费 API")),
        OutboundHost(host: "dashboard.flutterwave.com", purpose: L("Flutterwave 控制台")),
        OutboundHost(host: "developer.flutterwave.com", purpose: L("Flutterwave 文档")),
        OutboundHost(host: "api.openprovider.eu", purpose: L("Openprovider 发票 API")),
        OutboundHost(host: "invoice-exporter.api.stackit.cloud", purpose: L("STACKIT Invoice Exporter API")),
        OutboundHost(host: "identity.tyo1.conoha.io", purpose: L("ConoHa Identity API")),
        OutboundHost(host: "account.tyo1.conoha.io", purpose: L("ConoHa Account 账单 API")),
        OutboundHost(host: "identity.sin1.conoha.io", purpose: L("ConoHa Identity API")),
        OutboundHost(host: "account.sin1.conoha.io", purpose: L("ConoHa Account 账单 API")),
        OutboundHost(host: "identity.sjc1.conoha.io", purpose: L("ConoHa Identity API")),
        OutboundHost(host: "account.sjc1.conoha.io", purpose: L("ConoHa Account 账单 API")),
        OutboundHost(host: "identity.c3j1.conoha.io", purpose: L("ConoHa Identity API")),
        OutboundHost(host: "account.c3j1.conoha.io", purpose: L("ConoHa Account 账单 API")),
        OutboundHost(host: "www.conoha.jp", purpose: L("ConoHa 控制台")),
        OutboundHost(host: "doc.conoha.jp", purpose: L("ConoHa 文档")),
        OutboundHost(host: "identity.tyo1.cloud.z.com", purpose: L("Z.com Cloud Identity API")),
        OutboundHost(host: "account.tyo1.cloud.z.com", purpose: L("Z.com Cloud Account 账单 API")),
        OutboundHost(host: "cloud.z.com", purpose: L("Z.com Cloud 控制台")),
        OutboundHost(host: "your.idcfcloud.com", purpose: L("IDCF Cloud 账单 API")),
        OutboundHost(host: "www.idcf.jp", purpose: L("IDCF Cloud 控制台")),
        OutboundHost(host: "api.autodns.com", purpose: L("InterNetX AutoDNS 发票 API")),
        OutboundHost(host: "help.internetx.com", purpose: L("InterNetX 文档")),
        OutboundHost(host: "www.internetx.com", purpose: L("InterNetX 控制台")),
        OutboundHost(host: "api01.melbicom.net", purpose: L("Melbicom 账单 API")),
        OutboundHost(host: "docs.api.melbicom.net", purpose: L("Melbicom 文档")),
        OutboundHost(host: "www.melbicom.net", purpose: L("Melbicom 控制台")),
        OutboundHost(host: "billing.time4vps.com", purpose: L("Time4VPS 账单 API")),
        OutboundHost(host: "www.time4vps.com", purpose: L("Time4VPS 控制台")),
        OutboundHost(host: "app.bitlaunch.io", purpose: L("BitLaunch 账单 API")),
        OutboundHost(host: "developers.bitlaunch.io", purpose: L("BitLaunch 文档")),
        OutboundHost(host: "core.hivelocity.net", purpose: L("Hivelocity 账单 API")),
        OutboundHost(host: "developers.hivelocity.net", purpose: L("Hivelocity 文档")),
        OutboundHost(host: "my.hivelocity.net", purpose: L("Hivelocity 控制台")),
        OutboundHost(host: "auth.scalingo.com", purpose: L("Scalingo token 交换")),
        OutboundHost(host: "api.osc-fr1.scalingo.com", purpose: L("Scalingo 账单 API")),
        OutboundHost(host: "dashboard.scalingo.com", purpose: L("Scalingo 控制台")),
        OutboundHost(host: "developers.scalingo.com", purpose: L("Scalingo 文档")),
        OutboundHost(host: "auth.upsun.com", purpose: L("Upsun OAuth")),
        OutboundHost(host: "api.upsun.com", purpose: L("Upsun 账单 API")),
        OutboundHost(host: "console.upsun.com", purpose: L("Upsun 控制台")),
        OutboundHost(host: "developer.upsun.com", purpose: L("Upsun 文档")),
        OutboundHost(host: "billingapi.apigw.ntruss.com", purpose: L("NAVER Cloud 账单 API")),
        OutboundHost(host: "console.ncloud.com", purpose: L("NAVER Cloud 控制台")),
        OutboundHost(host: "api.ncloud-docs.com", purpose: L("NAVER Cloud 文档")),
        OutboundHost(host: "api.nomos.energy", purpose: L("Nomos 账单 API")),
        OutboundHost(host: "nomos.energy", purpose: L("Nomos 官网")),
        OutboundHost(host: "docs.nomos.energy", purpose: L("Nomos 文档")),
        OutboundHost(host: "api.dnscale.eu", purpose: L("DNScale 账单 API")),
        OutboundHost(host: "dnscale.eu", purpose: L("DNScale 官网")),
        OutboundHost(host: "formspring.io", purpose: L("Formspring 账单 API")),
        OutboundHost(host: "my.hostcircle.com", purpose: L("Hostcircle 账单 API")),
        OutboundHost(host: "hostbill.loginet.ee", purpose: L("Loginet 账单 API")),
        OutboundHost(host: "loginet.ee", purpose: L("Loginet 官网")),

        OutboundHost(host: "api.idcloudhost.com", purpose: L("IDCloudHost 账单 API")),
        OutboundHost(host: "idcloudhost.com", purpose: L("IDCloudHost 官网")),
        OutboundHost(host: "api-kr.iwinv.kr", purpose: L("iwinv 账单 API")),
        OutboundHost(host: "api.iwinv.kr", purpose: L("iwinv API 文档")),
        OutboundHost(host: "www.iwinv.kr", purpose: L("iwinv 官网")),
        OutboundHost(host: "frank-graphql-prod.graphcdn.app", purpose: L("Frank Energie GraphQL")),
        OutboundHost(host: "www.frankenergie.nl", purpose: L("Frank Energie 官网")),
        OutboundHost(host: "api.dilmune.com", purpose: L("Dilmune 账单 API")),
        OutboundHost(host: "docs.dilmune.com", purpose: L("Dilmune API 文档")),
        OutboundHost(host: "dilmune.com", purpose: L("Dilmune 官网")),
        OutboundHost(host: "api.hubble.com", purpose: L("Hubble 账单 API")),
        OutboundHost(host: "hubble.com", purpose: L("Hubble 官网与文档")),
        OutboundHost(host: "app.files.com", purpose: L("Files.com 账单 API")),
        OutboundHost(host: "www.files.com", purpose: L("Files.com 官网")),
        OutboundHost(host: "developers.files.com", purpose: L("Files.com API 文档")),
        OutboundHost(host: "api.doit.com", purpose: L("DoiT 账单 API")),
        OutboundHost(host: "www.doit.com", purpose: L("DoiT 官网")),
        OutboundHost(host: "developer.doit.com", purpose: L("DoiT API 文档")),
        OutboundHost(host: "console.doit.com", purpose: L("DoiT 控制台")),
        OutboundHost(host: "api.timeweb.cloud", purpose: L("Timeweb Cloud 账单 API")),
        OutboundHost(host: "timeweb.cloud", purpose: L("Timeweb Cloud 官网")),
        OutboundHost(host: "api.cloudheed.com", purpose: L("Cloudheed 账单 API")),
        OutboundHost(host: "cloudheed.com", purpose: L("Cloudheed 官网")),
        OutboundHost(host: "docs.cloudheed.com", purpose: L("Cloudheed 文档")),
        OutboundHost(host: "api.sevalla.com", purpose: L("Sevalla 账单 API")),
        OutboundHost(host: "sevalla.com", purpose: L("Sevalla 官网")),
        OutboundHost(host: "api-docs.sevalla.com", purpose: L("Sevalla 文档")),
        OutboundHost(host: "my.catalystvm.com", purpose: L("CatalystVM 账单 API")),
        OutboundHost(host: "catalystvm.com", purpose: L("CatalystVM 官网")),
        OutboundHost(host: "my.oxahost.com", purpose: L("Oxahost 账单 API")),
        OutboundHost(host: "oxahost.com", purpose: L("Oxahost 官网")),
        OutboundHost(host: "api.fiskil.com", purpose: L("Fiskil 账单 API")),
        OutboundHost(host: "fiskil.com", purpose: L("Fiskil 官网")),
        OutboundHost(host: "docs.fiskil.com", purpose: L("Fiskil 文档")),
        OutboundHost(host: "api.3plguys.com", purpose: L("3PLGuys 账单 API")),
        OutboundHost(host: "3plguys.com", purpose: L("3PLGuys 官网")),
        OutboundHost(host: "developer.3plguys.com", purpose: L("3PLGuys 文档")),
        OutboundHost(host: "external.pleo.io", purpose: L("Pleo 账单 API")),
        OutboundHost(host: "www.pleo.io", purpose: L("Pleo 官网")),
        OutboundHost(host: "developers.pleo.io", purpose: L("Pleo 文档")),
        OutboundHost(host: "rest.cerebrium.ai", purpose: L("Cerebrium 账单 API")),
        OutboundHost(host: "dashboard.cerebrium.ai", purpose: L("Cerebrium 控制台")),
        OutboundHost(host: "cerebrium.ai", purpose: L("Cerebrium 文档")),
        OutboundHost(host: "app.shipmondo.com", purpose: L("Shipmondo 账单 API")),
        OutboundHost(host: "sandbox.shipmondo.com", purpose: L("Shipmondo 沙箱")),
        OutboundHost(host: "shipmondo.dev", purpose: L("Shipmondo 文档")),
        OutboundHost(host: "shipmondo.com", purpose: L("Shipmondo 官网")),
        OutboundHost(host: "panel.sendcloud.sc", purpose: L("Sendcloud 账单 API")),
        OutboundHost(host: "account.sendcloud.com", purpose: L("Sendcloud OAuth")),
        OutboundHost(host: "sendcloud.dev", purpose: L("Sendcloud 文档")),
        OutboundHost(host: "sendcloud.com", purpose: L("Sendcloud 官网")),
        OutboundHost(host: "business.ap-southeast-1.aliyuncs.com", purpose: L("Alibaba Cloud 国际站 BSS 账单 API")),
        OutboundHost(host: "business.aliyuncs.com", purpose: L("Alibaba Cloud 国内站 BSS 账单 API")),
        OutboundHost(host: "usercenter2.aliyun.com", purpose: L("Alibaba Cloud 费用中心")),
        OutboundHost(host: "ram.console.aliyun.com", purpose: L("Alibaba Cloud RAM AccessKey")),
        OutboundHost(host: "www.alibabacloud.com", purpose: L("Alibaba Cloud 国际站文档")),
        OutboundHost(host: "billing.volcengineapi.com", purpose: L("火山引擎费用中心账单 API")),
        OutboundHost(host: "console.volcengine.com", purpose: L("火山引擎控制台 / IAM AccessKey")),
        OutboundHost(host: "www.volcengine.com", purpose: L("火山引擎文档")),
        OutboundHost(host: "bill-union.api.ksyun.com", purpose: L("金山云费用账单 API")),
        OutboundHost(host: "bill.console.ksyun.com", purpose: L("金山云费用中心")),
        OutboundHost(host: "ucenter.console.ksyun.com", purpose: L("金山云 AccessKey")),
        OutboundHost(host: "docs.ksyun.com", purpose: L("金山云文档")),
        OutboundHost(host: "billing.tencentcloudapi.com", purpose: L("腾讯云账单 API")),
        OutboundHost(host: "billing.intl.tencentcloudapi.com", purpose: L("腾讯云国际站账单 API")),
        OutboundHost(host: "console.cloud.tencent.com", purpose: L("腾讯云控制台 / CAM 密钥")),
        OutboundHost(host: "cloud.tencent.com", purpose: L("腾讯云文档")),
        OutboundHost(host: "eu1.make.com", purpose: L("Make 组织付款 API")),
        OutboundHost(host: "eu2.make.com", purpose: L("Make 组织付款 API")),
        OutboundHost(host: "us1.make.com", purpose: L("Make 组织付款 API")),
        OutboundHost(host: "us2.make.com", purpose: L("Make 组织付款 API")),
        OutboundHost(host: "eu1.make.celonis.com", purpose: L("Make Celonis 区站 API")),
        OutboundHost(host: "us1.make.celonis.com", purpose: L("Make Celonis 区站 API")),
        OutboundHost(host: "developers.make.com", purpose: L("Make 文档")),
        OutboundHost(host: "www.make.com", purpose: L("Make 官网")),
        OutboundHost(host: "api.glesys.com", purpose: L("GleSYS 账单 API")),
        OutboundHost(host: "api.redislabs.com", purpose: L("Redis Cloud 账单 API")),
        OutboundHost(host: "eu.app.unleash-hosted.com", purpose: L("Unleash Hosted EU 账单 API")),
        OutboundHost(host: "us.app.unleash-hosted.com", purpose: L("Unleash Hosted US 账单 API")),
        OutboundHost(host: "app.unleash-hosted.com", purpose: L("Unleash Hosted 账单 API")),
        OutboundHost(host: "zrh.cloudsigma.com", purpose: L("CloudSigma ZRH 账单 API")),
        OutboundHost(host: "sjc.cloudsigma.com", purpose: L("CloudSigma SJC 账单 API")),
        OutboundHost(host: "lhr.cloudsigma.com", purpose: L("CloudSigma LHR 账单 API")),
        OutboundHost(host: "mia.cloudsigma.com", purpose: L("CloudSigma MIA 账单 API")),
        OutboundHost(host: "wdc.cloudsigma.com", purpose: L("CloudSigma WDC 账单 API")),
        OutboundHost(host: "fra.cloudsigma.com", purpose: L("CloudSigma FRA 账单 API")),
        OutboundHost(host: "gva.cloudsigma.com", purpose: L("CloudSigma GVA 账单 API")),
        OutboundHost(host: "tyo.cloudsigma.com", purpose: L("CloudSigma TYO 账单 API")),
        OutboundHost(host: "hnl.cloudsigma.com", purpose: L("CloudSigma HNL 账单 API")),
        OutboundHost(host: "per.cloudsigma.com", purpose: L("CloudSigma PER 账单 API")),
        OutboundHost(host: "dus.cloudsigma.com", purpose: L("CloudSigma DUS 账单 API")),
        OutboundHost(host: "cwl.cloudsigma.com", purpose: L("CloudSigma CWL 账单 API")),
        OutboundHost(host: "crk.cloudsigma.com", purpose: L("CloudSigma CRK 账单 API")),
        OutboundHost(host: "mnl.cloudsigma.com", purpose: L("CloudSigma MNL 账单 API")),
        OutboundHost(host: "mnl2.cloudsigma.com", purpose: L("CloudSigma MNL2 账单 API")),
        OutboundHost(host: "api.together.ai", purpose: L("Together AI 账单 API")),
        OutboundHost(host: "docs.together.ai", purpose: L("Together AI 文档")),
        OutboundHost(host: "tollcat.app", purpose: L("分享卡片上二维码指向的地址")),
        OutboundHost(
            host: "api.tollcat.app",
            purpose: L("打赏留言、读数信箱、反馈、匿名页面计数与接入目录（不含任何 provider 凭据）")
        ),
        OutboundHost(
            host: "objects.githubusercontent.com",
            purpose: L("Mac 版更新包下载。更新清单本身放在 github.com 上这个项目的 Releases 里，App Store 版不会连这两处"),
            scope: .macDirectRelease
        ),
        OutboundHost(host: "admin.websupport.sk", purpose: L("Admin 控制台与账单页")),
        OutboundHost(host: "api.cloud.zilliz.com", purpose: L("Api 账单 API")),
        OutboundHost(host: "api.domeneshop.no", purpose: L("Api 账单 API")),
        OutboundHost(host: "app.northflank.com", purpose: L("App 控制台与账单页")),
        OutboundHost(host: "app.pdfshift.io", purpose: L("App 控制台与账单页")),
        OutboundHost(host: "app.redislabs.com", purpose: L("App 控制台与账单页")),
        OutboundHost(host: "app.surrealdb.com", purpose: L("App 控制台与账单页")),
        OutboundHost(host: "client.active24.com", purpose: L("Client 控制台与账单页")),
        OutboundHost(host: "docs.voltagepark.com", purpose: L("Voltage Park 文档")),
        OutboundHost(host: "cloud.voltagepark.com", purpose: L("Cloud 控制台与文档")),
        OutboundHost(host: "cloud.zilliz.com", purpose: L("Cloud 控制台与文档")),
        OutboundHost(host: "console.soniox.com", purpose: L("Console 控制台与账单页")),
        OutboundHost(host: "control.vps.net", purpose: L("Control 控制台与账单页")),
        OutboundHost(host: "customer.glesys.com", purpose: L("Customer 控制台与账单页")),
        OutboundHost(host: "developers.printful.com", purpose: L("Developers API 文档")),
        OutboundHost(host: "dm.realtimeregister.com", purpose: L("Dm 控制台与文档")),
        OutboundHost(host: "docs.cloudsigma.com", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.getunleash.io", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.openprovider.com", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.pdfshift.io", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.quay.io", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.stackit.cloud", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.surrealdb.com", purpose: L("Docs API 文档")),
        OutboundHost(host: "docs.zilliz.com", purpose: L("Docs API 文档")),
        OutboundHost(host: "gcore.com", purpose: L("Gcore 控制台与文档")),
        OutboundHost(host: "go.postman.co", purpose: L("Go 控制台与账单页")),
        OutboundHost(host: "igor.sbgenomics.com", purpose: L("Igor 控制台与文档")),
        OutboundHost(host: "learning.postman.com", purpose: L("Learning API 文档")),
        OutboundHost(host: "northflank.com", purpose: L("Northflank 控制台与文档")),
        OutboundHost(host: "portal.stackit.cloud", purpose: L("Portal 控制台与账单页")),
        OutboundHost(host: "quay.io", purpose: L("Quay 控制台与文档")),
        OutboundHost(host: "rcp.openprovider.eu", purpose: L("Rcp 控制台与文档")),
        OutboundHost(host: "redis.io", purpose: L("Redis 控制台与文档")),
        OutboundHost(host: "rest.websupport.se", purpose: L("Rest 控制台与文档")),
        OutboundHost(host: "smsc.ru", purpose: L("Smsc 控制台与文档")),
        OutboundHost(host: "soniox.com", purpose: L("Soniox 控制台与文档")),
        OutboundHost(host: "ui.cloudsigma.com", purpose: L("Ui 控制台与文档")),
        OutboundHost(host: "www.binarylane.com.au", purpose: L("Binarylane 控制台与文档")),
        OutboundHost(host: "www.cm.com", purpose: L("Cm 控制台与文档")),
        OutboundHost(host: "www.domeneshop.no", purpose: L("Domeneshop 控制台与文档")),
        OutboundHost(host: "www.getunleash.io", purpose: L("Getunleash 控制台与文档")),
        OutboundHost(host: "www.simply.com", purpose: L("Simply 控制台与文档")),
        OutboundHost(host: "www.tierpoint.com", purpose: L("Tierpoint 控制台与文档")),
        OutboundHost(host: "developer.orange.com", purpose: L("Orange Developer 控制台")),
        OutboundHost(host: "studio.mittwald.de", purpose: L("mittwald mStudio")),
        OutboundHost(host: "marketplace.zoom.us", purpose: L("Zoom App Marketplace")),
        OutboundHost(host: "dashboard.prodigi.com", purpose: L("Prodigi 控制台与 API Key")),
        OutboundHost(host: "kb.leaseweb.com", purpose: L("Leaseweb API Key 文档")),
        OutboundHost(host: "phoenixnap.com", purpose: L("phoenixNAP BMC 凭据文档")),
        OutboundHost(host: "id.magalu.com", purpose: L("Magalu Cloud API Key 页")),
        OutboundHost(host: "one.i3d.net", purpose: L("i3D.net API Keys 页")),
        OutboundHost(host: "app.datapacket.com", purpose: L("DataPacket 客户面板与 API Key")),
        OutboundHost(host: "compute.cudo.org", purpose: L("CUDO Compute 控制台与 API Key")),
        OutboundHost(host: "app.shipwell.com", purpose: L("Shipwell 控制台与 API Token")),
        OutboundHost(host: "app.mysendingbox.fr", purpose: L("MySendingBox API 密钥页")),
        OutboundHost(host: "dash.stannp.com", purpose: L("Stannp 控制台与文档")),
        OutboundHost(host: "ap.www.namecheap.com", purpose: L("Namecheap 控制台与 API 文档")),
        OutboundHost(host: "account.surrealdb.com", purpose: L("SurrealDB 账户门户")),
        OutboundHost(host: "dashboard.voltagepark.com", purpose: L("Voltage Park 控制台")),
        OutboundHost(host: "support.openprovider.eu", purpose: L("Openprovider 启用 API 说明")),
        OutboundHost(host: "home.binarylane.com.au", purpose: L("Binarylane 控制台与文档")),
        OutboundHost(host: "studio.mixpeek.com", purpose: L("Mixpeek Studio 控制台")),
        OutboundHost(host: "ermes.cloudcenter.seeweb.it", purpose: L("Seeweb Ermes 控制台")),
        OutboundHost(host: "www.saas.parasail.io", purpose: L("Parasail API Keys 页")),
        OutboundHost(host: "business.armadadelivery.com", purpose: L("Armada Delivery 商家控制台")),
        OutboundHost(host: "www.easypost.com", purpose: L("EasyPost API Keys 页")),
        OutboundHost(host: "portal.goshippo.com", purpose: L("Shippo API Portal 签发 token")),
        OutboundHost(host: "support.conoha.jp", purpose: L("ConoHa 签发 API 用户文档")),
        OutboundHost(host: "cloud.glesys.com", purpose: L("GleSYS Cloud 签发 API key")),
        OutboundHost(host: "dashboard.shipengine.com", purpose: L("ShipStation API 签发 API Key")),
        OutboundHost(host: "www.shipengine.com", purpose: L("ShipStation API 认证文档")),
        OutboundHost(host: "dashboard.thanks.io", purpose: L("thanks.io 签发 Personal Access Token")),
        OutboundHost(host: "support.dnsimple.com", purpose: L("DNSimple Access Token 文档")),
        OutboundHost(host: "console.idcfcloud.com", purpose: L("IDCF Cloud 签发 API Key")),
        OutboundHost(host: "console.iwinv.kr", purpose: L("iwinv 控制台")),
        OutboundHost(host: "cloud.dilmune.com", purpose: L("Dilmune Portal 签发 API Key")),
        OutboundHost(host: "dash.hubble.com", purpose: L("Hubble 签发 API Token")),
        OutboundHost(host: "dashboard.nomos.energy", purpose: L("Nomos 控制台")),
        OutboundHost(host: "app.doit.com", purpose: L("DoiT 控制台")),
        OutboundHost(host: "console.fiskil.com", purpose: L("Fiskil 控制台")),
        OutboundHost(host: "customer.active24.com", purpose: L("Active24 API Token 管理")),
        OutboundHost(host: "app.inference.sh", purpose: L("inference.sh 签发 API Key")),
        OutboundHost(host: "doc.scalingo.com", purpose: L("Scalingo 账户设置文档")),
        OutboundHost(host: "console.idcloudhost.com", purpose: L("IDCloudHost 控制台签发 API Token")),
        OutboundHost(host: "app.pleo.io", purpose: L("Pleo 控制台签发 API Key")),
        OutboundHost(host: "www.websupport.sk", purpose: L("Websupport API 密钥说明")),
        OutboundHost(host: "docs.gcore.com", purpose: L("Gcore API tokens 文档")),
        OutboundHost(host: "app.sevalla.com", purpose: L("Sevalla API Keys 页")),
        OutboundHost(host: "app.sendcloud.com", purpose: L("Sendcloud API 集成页")),
        OutboundHost(host: "uc.console.ksyun.com", purpose: L("金山云 IAM AccessKey")),
    ]

    public static let visible: [OutboundHost] = all.filter { $0.isActiveHere }

    public static let reservedHosts: Set<String> = [
        "example.invalid",
        "meter.invalid",
    ]

    public static let declaredHosts: Set<String> = Set(visible.map { $0.host })

    public static let allowedHosts: Set<String> = declaredHosts.union(reservedHosts)

    /// 白名单只认 https。明文 http 会把密钥头原样送出去——iOS 的 ATS 大多会拦，
    /// Android / Windows 两个壳没有等价保护，所以判定放在这一层而不是靠平台。
    public static func contains(_ url: URL) -> Bool {
        guard url.scheme == "https" else { return false }
        guard let host = url.host, !host.isEmpty else { return false }
        return allowedHosts.contains(host)
    }
}
