package com.zhechengqi.tollcat

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.zhechengqi.tollcat.ui.ContrastTier
import com.zhechengqi.tollcat.ui.TollCatAccent

/**
 * TollCat 蓝品牌静态方案，MCU 离线生成（scratchpad fonts/ 下的生成脚本）：
 * seed = 图标靛蓝 #5556D6，tertiary = 图标分段青 #00687A；primary/tertiary 用
 * seed 原生 chroma 的 palette（等价 MTB「stay true」，复现 canon #4B4DC8 一族），
 * secondary / 中性面走 TonalSpot 配方。三档对比度对应 MCU contrast level 0 / 0.5 / 1，
 * 与系统「对比度」设置（Android 14+）对齐——动态取色由系统自带对比档，这套只服务品牌模式。
 * 色值是生成物，不要手改；调整 seed 或配方后整文件重新生成。
 */
internal fun tollCatBrandScheme(dark: Boolean, contrast: ContrastTier): ColorScheme = when {
    dark && contrast == ContrastTier.High -> tollCatBrandDarkHigh
    dark && contrast == ContrastTier.Medium -> tollCatBrandDarkMedium
    dark -> tollCatBrandDarkStd
    contrast == ContrastTier.High -> tollCatBrandLightHigh
    contrast == ContrastTier.Medium -> tollCatBrandLightMedium
    else -> tollCatBrandLightStd
}

/** spendDown 语义绿（MCU palette tone 40/100/90/10 浅、80/20/30/90 深），两主题语义恒定。 */
internal fun tollCatSpendDown(dark: Boolean): TollCatAccent = if (dark) spendDownDark else spendDownLight

private val tollCatBrandLightStd = lightColorScheme(
    primary = Color(0xFF4C4DCD),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE1DFFF),
    onPrimaryContainer = Color(0xFF3331B5),
    inversePrimary = Color(0xFFC1C1FF),
    secondary = Color(0xFF5D5C72),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE2E0F9),
    onSecondaryContainer = Color(0xFF454559),
    tertiary = Color(0xFF00687A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFABEDFF),
    onTertiaryContainer = Color(0xFF004E5C),
    background = Color(0xFFFCF8FF),
    onBackground = Color(0xFF1B1B21),
    surface = Color(0xFFFCF8FF),
    onSurface = Color(0xFF1B1B21),
    surfaceVariant = Color(0xFFE4E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    surfaceTint = Color(0xFF4C4DCD),
    inverseSurface = Color(0xFF303036),
    inverseOnSurface = Color(0xFFF3EFF7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF777680),
    outlineVariant = Color(0xFFC8C5D0),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8FF),
    surfaceDim = Color(0xFFDCD9E0),
    surfaceContainer = Color(0xFFF0ECF4),
    surfaceContainerHigh = Color(0xFFEAE7EF),
    surfaceContainerHighest = Color(0xFFE4E1E9),
    surfaceContainerLow = Color(0xFFF6F2FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFE1DFFF),
    primaryFixedDim = Color(0xFFC1C1FF),
    onPrimaryFixed = Color(0xFF08006C),
    onPrimaryFixedVariant = Color(0xFF3331B5),
    secondaryFixed = Color(0xFFE2E0F9),
    secondaryFixedDim = Color(0xFFC6C4DD),
    onSecondaryFixed = Color(0xFF1A1A2C),
    onSecondaryFixedVariant = Color(0xFF454559),
    tertiaryFixed = Color(0xFFABEDFF),
    tertiaryFixedDim = Color(0xFF86D2E6),
    onTertiaryFixed = Color(0xFF001F26),
    onTertiaryFixedVariant = Color(0xFF004E5C),
)

private val tollCatBrandLightMedium = lightColorScheme(
    primary = Color(0xFF1F19A5),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF5C5DDD),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFFC1C1FF),
    secondary = Color(0xFF343448),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF6C6B81),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF003C47),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF217789),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFFCF8FF),
    onBackground = Color(0xFF1B1B21),
    surface = Color(0xFFFCF8FF),
    onSurface = Color(0xFF111116),
    surfaceVariant = Color(0xFFE4E1EC),
    onSurfaceVariant = Color(0xFF36353E),
    surfaceTint = Color(0xFF4C4DCD),
    inverseSurface = Color(0xFF303036),
    inverseOnSurface = Color(0xFFF3EFF7),
    error = Color(0xFF740006),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFCF2C27),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFF52515B),
    outlineVariant = Color(0xFF6D6C75),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8FF),
    surfaceDim = Color(0xFFC8C5CD),
    surfaceContainer = Color(0xFFEAE7EF),
    surfaceContainerHigh = Color(0xFFDFDBE3),
    surfaceContainerHighest = Color(0xFFD3D0D8),
    surfaceContainerLow = Color(0xFFF6F2FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFF5C5DDD),
    primaryFixedDim = Color(0xFF4242C3),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFFFFFFFF),
    secondaryFixed = Color(0xFF6C6B81),
    secondaryFixedDim = Color(0xFF535368),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFFFFFFF),
    tertiaryFixed = Color(0xFF217789),
    tertiaryFixedDim = Color(0xFF005D6E),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFFFFFFF),
)

private val tollCatBrandLightHigh = lightColorScheme(
    primary = Color(0xFF11009C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF3634B7),
    onPrimaryContainer = Color(0xFFFFFFFF),
    inversePrimary = Color(0xFFC1C1FF),
    secondary = Color(0xFF2A2A3D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF47475C),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF00313B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF00515F),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFFCF8FF),
    onBackground = Color(0xFF1B1B21),
    surface = Color(0xFFFCF8FF),
    onSurface = Color(0xFF000000),
    surfaceVariant = Color(0xFFE4E1EC),
    onSurfaceVariant = Color(0xFF000000),
    surfaceTint = Color(0xFF4C4DCD),
    inverseSurface = Color(0xFF303036),
    inverseOnSurface = Color(0xFFFFFFFF),
    error = Color(0xFF600004),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFF98000A),
    onErrorContainer = Color(0xFFFFFFFF),
    outline = Color(0xFF2C2B34),
    outlineVariant = Color(0xFF494851),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF8FF),
    surfaceDim = Color(0xFFBAB7BF),
    surfaceContainer = Color(0xFFE4E1E9),
    surfaceContainerHigh = Color(0xFFD6D3DB),
    surfaceContainerHighest = Color(0xFFC8C5CD),
    surfaceContainerLow = Color(0xFFF3EFF7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFF3634B7),
    primaryFixedDim = Color(0xFF1B12A2),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFFFFFFFF),
    secondaryFixed = Color(0xFF47475C),
    secondaryFixedDim = Color(0xFF313144),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFFFFFFF),
    tertiaryFixed = Color(0xFF00515F),
    tertiaryFixedDim = Color(0xFF003843),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFFFFFFF),
)

private val tollCatBrandDarkStd = darkColorScheme(
    primary = Color(0xFFC1C1FF),
    onPrimary = Color(0xFF180CA0),
    primaryContainer = Color(0xFF3331B5),
    onPrimaryContainer = Color(0xFFE1DFFF),
    inversePrimary = Color(0xFF4C4DCD),
    secondary = Color(0xFFC6C4DD),
    onSecondary = Color(0xFF2F2F42),
    secondaryContainer = Color(0xFF454559),
    onSecondaryContainer = Color(0xFFE2E0F9),
    tertiary = Color(0xFF86D2E6),
    onTertiary = Color(0xFF003640),
    tertiaryContainer = Color(0xFF004E5C),
    onTertiaryContainer = Color(0xFFABEDFF),
    background = Color(0xFF131318),
    onBackground = Color(0xFFE4E1E9),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFE4E1E9),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC8C5D0),
    surfaceTint = Color(0xFFC1C1FF),
    inverseSurface = Color(0xFFE4E1E9),
    inverseOnSurface = Color(0xFF303036),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF918F9A),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF39383F),
    surfaceDim = Color(0xFF131318),
    surfaceContainer = Color(0xFF1F1F25),
    surfaceContainerHigh = Color(0xFF2A292F),
    surfaceContainerHighest = Color(0xFF35343A),
    surfaceContainerLow = Color(0xFF1B1B21),
    surfaceContainerLowest = Color(0xFF0E0E13),
    primaryFixed = Color(0xFFE1DFFF),
    primaryFixedDim = Color(0xFFC1C1FF),
    onPrimaryFixed = Color(0xFF08006C),
    onPrimaryFixedVariant = Color(0xFF3331B5),
    secondaryFixed = Color(0xFFE2E0F9),
    secondaryFixedDim = Color(0xFFC6C4DD),
    onSecondaryFixed = Color(0xFF1A1A2C),
    onSecondaryFixedVariant = Color(0xFF454559),
    tertiaryFixed = Color(0xFFABEDFF),
    tertiaryFixedDim = Color(0xFF86D2E6),
    onTertiaryFixed = Color(0xFF001F26),
    onTertiaryFixedVariant = Color(0xFF004E5C),
)

private val tollCatBrandDarkMedium = darkColorScheme(
    primary = Color(0xFFDAD9FF),
    onPrimary = Color(0xFF0E0089),
    primaryContainer = Color(0xFF8183FF),
    onPrimaryContainer = Color(0xFF000000),
    inversePrimary = Color(0xFF3433B6),
    secondary = Color(0xFFDCDAF3),
    onSecondary = Color(0xFF242436),
    secondaryContainer = Color(0xFF908FA5),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFF9CE8FD),
    onTertiary = Color(0xFF002A33),
    tertiaryContainer = Color(0xFF4D9BAE),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF131318),
    onBackground = Color(0xFFE4E1E9),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFDEDBE6),
    surfaceTint = Color(0xFFC1C1FF),
    inverseSurface = Color(0xFFE4E1E9),
    inverseOnSurface = Color(0xFF2A292F),
    error = Color(0xFFFFD2CC),
    onError = Color(0xFF540003),
    errorContainer = Color(0xFFFF5449),
    onErrorContainer = Color(0xFF000000),
    outline = Color(0xFFB3B0BB),
    outlineVariant = Color(0xFF918F99),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF45444A),
    surfaceDim = Color(0xFF131318),
    surfaceContainer = Color(0xFF28272D),
    surfaceContainerHigh = Color(0xFF333238),
    surfaceContainerHighest = Color(0xFF3E3D43),
    surfaceContainerLow = Color(0xFF1D1D23),
    surfaceContainerLowest = Color(0xFF07070C),
    primaryFixed = Color(0xFFE1DFFF),
    primaryFixedDim = Color(0xFFC1C1FF),
    onPrimaryFixed = Color(0xFF04004D),
    onPrimaryFixedVariant = Color(0xFF1F19A5),
    secondaryFixed = Color(0xFFE2E0F9),
    secondaryFixedDim = Color(0xFFC6C4DD),
    onSecondaryFixed = Color(0xFF0F0F21),
    onSecondaryFixedVariant = Color(0xFF343448),
    tertiaryFixed = Color(0xFFABEDFF),
    tertiaryFixedDim = Color(0xFF86D2E6),
    onTertiaryFixed = Color(0xFF001419),
    onTertiaryFixedVariant = Color(0xFF003C47),
)

private val tollCatBrandDarkHigh = darkColorScheme(
    primary = Color(0xFFF1EEFF),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFBCBDFF),
    onPrimaryContainer = Color(0xFF02003C),
    inversePrimary = Color(0xFF3433B6),
    secondary = Color(0xFFF1EEFF),
    onSecondary = Color(0xFF000000),
    secondaryContainer = Color(0xFFC2C0D9),
    onSecondaryContainer = Color(0xFF09091B),
    tertiary = Color(0xFFD6F5FF),
    onTertiary = Color(0xFF000000),
    tertiaryContainer = Color(0xFF82CEE2),
    onTertiaryContainer = Color(0xFF000D12),
    background = Color(0xFF131318),
    onBackground = Color(0xFFE4E1E9),
    surface = Color(0xFF131318),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFFFFFFF),
    surfaceTint = Color(0xFFC1C1FF),
    inverseSurface = Color(0xFFE4E1E9),
    inverseOnSurface = Color(0xFF000000),
    error = Color(0xFFFFECE9),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFFFFAEA4),
    onErrorContainer = Color(0xFF220001),
    outline = Color(0xFFF2EEFA),
    outlineVariant = Color(0xFFC4C1CC),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF504F56),
    surfaceDim = Color(0xFF131318),
    surfaceContainer = Color(0xFF303036),
    surfaceContainerHigh = Color(0xFF3B3B41),
    surfaceContainerHighest = Color(0xFF47464C),
    surfaceContainerLow = Color(0xFF1F1F25),
    surfaceContainerLowest = Color(0xFF000000),
    primaryFixed = Color(0xFFE1DFFF),
    primaryFixedDim = Color(0xFFC1C1FF),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF04004D),
    secondaryFixed = Color(0xFFE2E0F9),
    secondaryFixedDim = Color(0xFFC6C4DD),
    onSecondaryFixed = Color(0xFF000000),
    onSecondaryFixedVariant = Color(0xFF0F0F21),
    tertiaryFixed = Color(0xFFABEDFF),
    tertiaryFixedDim = Color(0xFF86D2E6),
    onTertiaryFixed = Color(0xFF000000),
    onTertiaryFixedVariant = Color(0xFF001419),
)

private val spendDownLight = TollCatAccent(main = Color(0xFF1B6D24), onMain = Color(0xFFFFFFFF), container = Color(0xFFA3F69C), onContainer = Color(0xFF002204))
private val spendDownDark = TollCatAccent(main = Color(0xFF88D982), onMain = Color(0xFF003909), container = Color(0xFF005312), onContainer = Color(0xFFA3F69C))
